// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HungryTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DeathMatch")]
    public partial class DeathMatchFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "DeathMatch.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "DeathMatch", "How do we handle a death match?", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 player death match on 2x2 board")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async System.Threading.Tasks.Task _2PlayerDeathMatchOn2X2Board()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 player death match on 2x2 board", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("the game state is Joining", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.GivenAsync("p1 joins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.AndAsync("p2 joins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("the game starts with 2 rows, 2 columns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.ThenAsync("the game state is Eating", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
 await testRunner.WhenAsync("p1 moves Left and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
 await testRunner.AndAsync("p1\'s location is (0,0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.WhenAsync("p2 moves Left and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.ThenAsync("p2\'s score is 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
 await testRunner.AndAsync("p2\'s location is (1,0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("the game state is Battle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.WhenAsync("p2 moves Up and attacks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
 await testRunner.ThenAsync("p1 is removed from the board", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
 await testRunner.AndAsync("p2\'s score is 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("p2 is declared winner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("the game state is GameOver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 player death match on 3x3 board")]
        public async System.Threading.Tasks.Task _3PlayerDeathMatchOn3X3Board()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 player death match on 3x3 board", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.GivenAsync("the game state is Joining", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
 await testRunner.GivenAsync("p1 joins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
 await testRunner.AndAsync("p2 joins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("p3 joins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("the game starts with 3 rows, 3 columns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.ThenAsync("the game state is Eating", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
 await testRunner.WhenAsync("p1 moves Left and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
 await testRunner.AndAsync("p1\'s location is (0,0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.WhenAsync("p2 moves Left and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 await testRunner.ThenAsync("p2\'s score is 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 await testRunner.AndAsync("p2\'s location is (1,0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table1.AddRow(new string[] {
                            "1_·"});
                table1.AddRow(new string[] {
                            "2_3"});
                table1.AddRow(new string[] {
                            "···"});
#line 38
 await testRunner.AndAsync("the board looks like", ((string)(null)), table1, "And ");
#line hidden
#line 43
 await testRunner.WhenAsync("p2 moves Down and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
 await testRunner.ThenAsync("p2\'s score is 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 await testRunner.AndAsync("p2\'s location is (2,0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table2.AddRow(new string[] {
                            "1_·"});
                table2.AddRow(new string[] {
                            "__3"});
                table2.AddRow(new string[] {
                            "2··"});
#line 46
 await testRunner.AndAsync("the board looks like", ((string)(null)), table2, "And ");
#line hidden
#line 51
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
 await testRunner.ThenAsync("p2\'s score is 9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
 await testRunner.AndAsync("p2\'s location is (2,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table3.AddRow(new string[] {
                            "1_·"});
                table3.AddRow(new string[] {
                            "__3"});
                table3.AddRow(new string[] {
                            "_2·"});
#line 54
 await testRunner.AndAsync("the board looks like", ((string)(null)), table3, "And ");
#line hidden
#line 59
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 60
 await testRunner.ThenAsync("p2\'s score is 14", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 61
 await testRunner.AndAsync("p2\'s location is (2,2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table4.AddRow(new string[] {
                            "1_·"});
                table4.AddRow(new string[] {
                            "__3"});
                table4.AddRow(new string[] {
                            "__2"});
#line 62
 await testRunner.AndAsync("the board looks like", ((string)(null)), table4, "And ");
#line hidden
#line 67
 await testRunner.WhenAsync("p1 moves Right and does nothing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 68
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 69
 await testRunner.AndAsync("p1\'s location is (0,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table5.AddRow(new string[] {
                            "_1·"});
                table5.AddRow(new string[] {
                            "__3"});
                table5.AddRow(new string[] {
                            "__2"});
#line 70
 await testRunner.AndAsync("the board looks like", ((string)(null)), table5, "And ");
#line hidden
#line 75
 await testRunner.WhenAsync("p1 moves Right and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 76
 await testRunner.ThenAsync("p1\'s score is 7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
 await testRunner.AndAsync("p1\'s location is (0,2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("the game state is Battle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table6.AddRow(new string[] {
                            "__1"});
                table6.AddRow(new string[] {
                            "__3"});
                table6.AddRow(new string[] {
                            "__2"});
#line 79
 await testRunner.AndAsync("the board looks like", ((string)(null)), table6, "And ");
#line hidden
#line 84
 await testRunner.WhenAsync("p2 moves Left and does nothing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 85
 await testRunner.ThenAsync("p1\'s score is 7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
 await testRunner.AndAsync("p2\'s location is (2,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table7.AddRow(new string[] {
                            "__1"});
                table7.AddRow(new string[] {
                            "__3"});
                table7.AddRow(new string[] {
                            "_2_"});
#line 87
 await testRunner.AndAsync("the board looks like", ((string)(null)), table7, "And ");
#line hidden
#line 92
 await testRunner.WhenAsync("p2 moves Up and does nothing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
 await testRunner.ThenAsync("p2\'s location is (1,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table8.AddRow(new string[] {
                            "__1"});
                table8.AddRow(new string[] {
                            "_23"});
                table8.AddRow(new string[] {
                            "___"});
#line 94
 await testRunner.AndAsync("the board looks like", ((string)(null)), table8, "And ");
#line hidden
#line 99
 await testRunner.WhenAsync("p2 moves Up and does nothing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 100
 await testRunner.ThenAsync("p2\'s score is 14", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
 await testRunner.AndAsync("p2\'s location is (0,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table9.AddRow(new string[] {
                            "_21"});
                table9.AddRow(new string[] {
                            "__3"});
                table9.AddRow(new string[] {
                            "___"});
#line 102
 await testRunner.AndAsync("the board looks like", ((string)(null)), table9, "And ");
#line hidden
#line 107
 await testRunner.WhenAsync("p2 moves Right and attacks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 108
 await testRunner.ThenAsync("p2\'s score is 7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
 await testRunner.AndAsync("p2\'s location is (0,1)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table10.AddRow(new string[] {
                            "_2·"});
                table10.AddRow(new string[] {
                            "__3"});
                table10.AddRow(new string[] {
                            "___"});
#line 110
 await testRunner.AndAsync("the board looks like", ((string)(null)), table10, "And ");
#line hidden
#line 115
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
 await testRunner.AndAsync("p2\'s location is (0,2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table11.AddRow(new string[] {
                            "__2"});
                table11.AddRow(new string[] {
                            "__3"});
                table11.AddRow(new string[] {
                            "___"});
#line 118
 await testRunner.AndAsync("the board looks like", ((string)(null)), table11, "And ");
#line hidden
#line 123
 await testRunner.WhenAsync("p2 moves Down and attacks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 124
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
 await testRunner.AndAsync("p2\'s location is (0,2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Board State"});
                table12.AddRow(new string[] {
                            "__2"});
                table12.AddRow(new string[] {
                            "__·"});
                table12.AddRow(new string[] {
                            "___"});
#line 126
 await testRunner.AndAsync("the board looks like", ((string)(null)), table12, "And ");
#line hidden
#line 131
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
 await testRunner.AndAsync("p2 is declared winner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("the game state is GameOver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
