// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace HungryTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("DeathMatch")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class DeathMatchFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "DeathMatch", "How do we handle a death match?", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "DeathMatch.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DeathMatch.feature.ndjson", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2 player death match on 2x2 board")]
        [global::NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task _2PlayerDeathMatchOn2X2Board()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 player death match on 2x2 board", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("the game state is Joining", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.GivenAsync("p1 joins", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.AndAsync("p2 joins", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("the game starts with 2 rows, 2 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.ThenAsync("the game state is Eating", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
 await testRunner.WhenAsync("p1 moves Left and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
 await testRunner.AndAsync("p1\'s location is (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.WhenAsync("p2 moves Left and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.ThenAsync("p2\'s score is 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
 await testRunner.AndAsync("p2\'s location is (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("the game state is Battle", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.WhenAsync("p2 moves Up and attacks", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
 await testRunner.ThenAsync("p1 is removed from the board", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
 await testRunner.AndAsync("p2\'s score is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("p2 is declared winner", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("the game state is GameOver", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("3 player death match on 3x3 board")]
        public async global::System.Threading.Tasks.Task _3PlayerDeathMatchOn3X3Board()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3 player death match on 3x3 board", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.GivenAsync("the game state is Joining", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
 await testRunner.GivenAsync("p1 joins", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
 await testRunner.AndAsync("p2 joins", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("p3 joins", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("the game starts with 3 rows, 3 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.ThenAsync("the game state is Eating", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
 await testRunner.WhenAsync("p1 moves Left and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
 await testRunner.AndAsync("p1\'s location is (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.WhenAsync("p2 moves Left and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
 await testRunner.ThenAsync("p2\'s score is 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
 await testRunner.AndAsync("p2\'s location is (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table1.AddRow(new string[] {
                            "1_·"});
                table1.AddRow(new string[] {
                            "2_3"});
                table1.AddRow(new string[] {
                            "···"});
#line 38
 await testRunner.AndAsync("the board looks like", ((string)(null)), table1, "And ");
#line hidden
#line 43
 await testRunner.WhenAsync("p2 moves Down and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
 await testRunner.ThenAsync("p2\'s score is 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
 await testRunner.AndAsync("p2\'s location is (2,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table2.AddRow(new string[] {
                            "1_·"});
                table2.AddRow(new string[] {
                            "__3"});
                table2.AddRow(new string[] {
                            "2··"});
#line 46
 await testRunner.AndAsync("the board looks like", ((string)(null)), table2, "And ");
#line hidden
#line 51
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
 await testRunner.ThenAsync("p2\'s score is 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
 await testRunner.AndAsync("p2\'s location is (2,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table3.AddRow(new string[] {
                            "1_·"});
                table3.AddRow(new string[] {
                            "__3"});
                table3.AddRow(new string[] {
                            "_2·"});
#line 54
 await testRunner.AndAsync("the board looks like", ((string)(null)), table3, "And ");
#line hidden
#line 59
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
 await testRunner.ThenAsync("p2\'s score is 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 61
 await testRunner.AndAsync("p2\'s location is (2,2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table4.AddRow(new string[] {
                            "1_·"});
                table4.AddRow(new string[] {
                            "__3"});
                table4.AddRow(new string[] {
                            "__2"});
#line 62
 await testRunner.AndAsync("the board looks like", ((string)(null)), table4, "And ");
#line hidden
#line 67
 await testRunner.WhenAsync("p1 moves Right and does nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
 await testRunner.ThenAsync("p1\'s score is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 69
 await testRunner.AndAsync("p1\'s location is (0,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table5.AddRow(new string[] {
                            "_1·"});
                table5.AddRow(new string[] {
                            "__3"});
                table5.AddRow(new string[] {
                            "__2"});
#line 70
 await testRunner.AndAsync("the board looks like", ((string)(null)), table5, "And ");
#line hidden
#line 75
 await testRunner.WhenAsync("p1 moves Right and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
 await testRunner.ThenAsync("p1\'s score is 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
 await testRunner.AndAsync("p1\'s location is (0,2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("the game state is Battle", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table6.AddRow(new string[] {
                            "__1"});
                table6.AddRow(new string[] {
                            "__3"});
                table6.AddRow(new string[] {
                            "__2"});
#line 79
 await testRunner.AndAsync("the board looks like", ((string)(null)), table6, "And ");
#line hidden
#line 84
 await testRunner.WhenAsync("p2 moves Left and does nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
 await testRunner.ThenAsync("p1\'s score is 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
 await testRunner.AndAsync("p2\'s location is (2,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table7.AddRow(new string[] {
                            "__1"});
                table7.AddRow(new string[] {
                            "__3"});
                table7.AddRow(new string[] {
                            "_2_"});
#line 87
 await testRunner.AndAsync("the board looks like", ((string)(null)), table7, "And ");
#line hidden
#line 92
 await testRunner.WhenAsync("p2 moves Up and does nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
 await testRunner.ThenAsync("p2\'s location is (1,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table8.AddRow(new string[] {
                            "__1"});
                table8.AddRow(new string[] {
                            "_23"});
                table8.AddRow(new string[] {
                            "___"});
#line 94
 await testRunner.AndAsync("the board looks like", ((string)(null)), table8, "And ");
#line hidden
#line 99
 await testRunner.WhenAsync("p2 moves Up and does nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
 await testRunner.ThenAsync("p2\'s score is 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
 await testRunner.AndAsync("p2\'s location is (0,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table9.AddRow(new string[] {
                            "_21"});
                table9.AddRow(new string[] {
                            "__3"});
                table9.AddRow(new string[] {
                            "___"});
#line 102
 await testRunner.AndAsync("the board looks like", ((string)(null)), table9, "And ");
#line hidden
#line 107
 await testRunner.WhenAsync("p2 moves Right and attacks", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
 await testRunner.ThenAsync("p2\'s score is 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
 await testRunner.AndAsync("p2\'s location is (0,1)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table10.AddRow(new string[] {
                            "_2·"});
                table10.AddRow(new string[] {
                            "__3"});
                table10.AddRow(new string[] {
                            "___"});
#line 110
 await testRunner.AndAsync("the board looks like", ((string)(null)), table10, "And ");
#line hidden
#line 115
 await testRunner.WhenAsync("p2 moves Right and eats a pill", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
 await testRunner.AndAsync("p2\'s location is (0,2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table11.AddRow(new string[] {
                            "__2"});
                table11.AddRow(new string[] {
                            "__3"});
                table11.AddRow(new string[] {
                            "___"});
#line 118
 await testRunner.AndAsync("the board looks like", ((string)(null)), table11, "And ");
#line hidden
#line 123
 await testRunner.WhenAsync("p2 moves Down and attacks", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
 await testRunner.AndAsync("p2\'s location is (0,2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Board State"});
                table12.AddRow(new string[] {
                            "__2"});
                table12.AddRow(new string[] {
                            "__·"});
                table12.AddRow(new string[] {
                            "___"});
#line 126
 await testRunner.AndAsync("the board looks like", ((string)(null)), table12, "And ");
#line hidden
#line 131
 await testRunner.ThenAsync("p2\'s score is 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
 await testRunner.AndAsync("p2 is declared winner", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.AndAsync("the game state is GameOver", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
