# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - hungrygame

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Build / Publish
        run: dotnet publish HungryGame -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hungrygame'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5BDDFEE2C1244C62A86595514A4DE054 }}
          startup-command: 'dotnet HungryGame.dll'